version: '3'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:16
    ports:
      - '5433:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_ROOT_PASSWORD=root
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database
