"""add test

Revision ID: 33b3d283bf2c
Revises: 607460554aa4
Create Date: 2024-01-12 18:44:13.583591

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b3d283bf2c'
down_revision: Union[str, None] = '607460554aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('test2', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'test2')
    # ### end Alembic commands ###
