"""add test

Revision ID: 607460554aa4
Revises: 62b93600340d
Create Date: 2024-01-12 18:39:50.663792

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "607460554aa4"
down_revision: Union[str, None] = "62b93600340d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company", sa.Column("test1", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "test1")
    # ### end Alembic commands ###
